//! Ticket T04 item 3a — characterising `Fixed::exp` on **`x > 0`**.
//!
//! # The gap
//!
//! T02 measured `exp` only on `x ∈ [-45, 0]` and `fixed.rs`'s module header
//! says, verbatim, *"`exp` is also implemented for `x > 0` … T03 does not need
//! that branch; only `x ≤ 0` is covered by the accuracy table above."*
//!
//! **That is no longer true.** T03's `lmsr::b_small_softplus` evaluates
//! `b · e^x` as `exp(ln b + x)` — the trick that lets the minority weight
//! survive `~ln b` more units of skew than `e^x` alone. Its argument is
//! positive whenever `x > −ln b`, and at `b = B_MAX` with the branch's entry
//! condition `x ≤ −20` it reaches
//!
//! ```text
//! ln(1e12) − 20 = 27.63102… − 20 = +7.63102…
//! ```
//!
//! So the positive branch sits on the hot path of `cost`, `buy_cost`,
//! `sell_return` and `shares_for_cost` at every deeply skewed state, and the
//! 128-point golden table in `src/fixed.rs` does not contain a single point of
//! it.
//!
//! # What is measured here
//!
//! Two tables, generated by `tests/gen_exp_positive_golden.py` with `mpmath` at
//! 500 bits and committed under `tests/data/`:
//!
//! * [`EXP_POSITIVE_GOLDEN`] — 320 points of `exp(x)` for `x ∈ (0, ln 2^63)`,
//!   including **every multiple of the hard-coded `LN_2_RAW` and both of its
//!   neighbours**. Those are the range-reduction seams: `exp` splits
//!   `x = n·LN_2_RAW + r`, evaluates `e^-(ln2 − r)` and shifts left by `n+1`,
//!   so a mistake in the split shows up exactly there and nowhere else.
//! * [`SCALED_EXP_GOLDEN`] — 144 points of the composite `exp(ln b + x)` that
//!   `b_small_softplus` actually runs, over all six `b` decades and the `x`
//!   values that reach the branch. This measures the whole `ln → add → exp`
//!   chain end to end, which is what the LMSR's error actually depends on.
//!
//! # Why the bound is stated as a *relative* error
//!
//! On `x ≤ 0` the result is in `(0, 1]` and an absolute ulp count is the right
//! measure. On `x > 0` the result grows to `9.2e18`, and the algorithm's own
//! structure — evaluate `e^-r ∈ [1/2, 1]`, then shift left by `n+1` — makes the
//! error **proportional to the result**: an exact left shift multiplies the
//! series' ~2 ulp by `2^(n+1)`. Quoting ulps there would say "10^19 ulp" and
//! mean nothing. The relative figure is the invariant one, and it is the one
//! that propagates: `b_small_softplus` returns a value of magnitude `b·e^x`,
//! so its absolute error in base units is `b·e^x · ε`.
//!
//! # Measured result
//!
//! | table | domain | max rel err **measured** | asserted |
//! |---|---|---|---|
//! | `exp(x)` | `x ∈ (0, 7.7]` — reachable band | **2.8149e-19** (at `x = 7.222`) | ≤ 1.0e-18 |
//! | `exp(x)` | `x ∈ (0, 43.67)` — whole branch | **7.3489e-19** (at `x = 43.0`) | ≤ 3.0e-18 |
//! | `exp(ln b + x)` | the real `b_small_softplus` inputs | **2.8842e-18** (at `b = 1e10`, `x = −27`) | ≤ 6.0e-18 |
//!
//! **Verdict: the positive branch is as accurate as T02's `x ≤ 0` branch.**
//! `2.81e-19` on the reachable band is within 30% of the `2.17e-19` T02
//! measured for negative arguments, and the `2.88e-18` composite outlier is not
//! algorithmic — it is a single result of magnitude `0.0188` being one raw ulp
//! out, i.e. the fixed-point floor (`2^-64 / 0.0188 = 2.9e-18`) rather than any
//! error in `exp`.
//!
//! The figure that matters to the LMSR is the **absolute** one: the composite
//! carries at most **1.454e-15 base units** of error, against a `1`-base-unit
//! rounding step — 15 orders of magnitude of margin, so this branch cannot move
//! a rounded result.
//!
//! The tests recompute the maxima on every run and print them, so the numbers
//! above are measurements, not claims.

#[path = "data/exp_positive_golden.rs"]
mod golden;

use golden::{EXP_POSITIVE_GOLDEN, SCALED_EXP_GOLDEN};
use lmsr::{Fixed, FixedError, B_MAX, B_MIN};

// ---------------------------------------------------------------------------
// Asserted bounds
// ---------------------------------------------------------------------------

/// Relative error asserted for `exp(x)` over the band `b_small_softplus` can
/// actually reach, `x ∈ (0, 7.7]`.
///
/// The floor is set by three sources, all inherent to Q64.64 rather than to the
/// algorithm: the ~2 ulp of `exp_neg_series` on a result in `[1/2, 1]`
/// (`≤ 4·2^-64 = 2.2e-19` relative), the rounding of the hard-coded `LN_2_RAW`
/// (`0.211 ulp`, multiplied by `n+1 ≤ 12` in the range reduction → `1.4e-19`),
/// and the final rounding. **Measured: 2.8149e-19.** Asserted at **1.0e-18**,
/// ~3.6× the measurement — tight enough that a real regression trips it, loose
/// enough that a one-ulp change in a series term does not.
const REACHABLE_REL_BOUND: f64 = 1.0e-18;

/// The same over the entire positive branch out to `ln(2^63) ≈ 43.668`, where
/// `n + 1` reaches 63 and the `LN_2_RAW` residual is multiplied by 63.
/// **Measured: 7.3489e-19**, at `x = 43` exactly. Nothing in the LMSR goes
/// here; it is measured so a future caller has a number to rely on.
const FULL_REL_BOUND: f64 = 3.0e-18;

/// Relative error asserted for the composite `exp(ln b + x)` against
/// `b · e^x`. **Measured: 2.8842e-18** — and that worst case is the fixed-point
/// floor, not the algorithm: the result there has magnitude `0.0188`, where a
/// single raw ulp *is* `2.9e-18` relative. Larger than
/// [`REACHABLE_REL_BOUND`] anyway because `ln(b)`'s own error (up to 15 ulp =
/// `8.1e-19` absolute) enters the exponent and reappears as a relative error of
/// the same size on top of `exp`'s.
const COMPOSITE_REL_BOUND: f64 = 6.0e-18;

/// Absolute error asserted for the composite, in base units.
/// **Measured: 1.454e-15.** Asserted at `1e-9`, which is still six orders of
/// magnitude below the `1`-base-unit rounding step every public function
/// finishes with — i.e. this term provably cannot change a rounded answer.
const COMPOSITE_ABS_BOUND_UNITS: f64 = 1e-9;

/// `x ≤ 7.7` covers everything `b_small_softplus` can produce
/// (`ln(B_MAX) − 20 = 7.63102…`). Raw Q64.64.
const REACHABLE_MAX_RAW: i128 = 142_039_929_367_563_547_443;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

fn ulps(a: i128, b: i128) -> u128 {
    if a >= b {
        a.wrapping_sub(b) as u128
    } else {
        b.wrapping_sub(a) as u128
    }
}

fn rel(got: i128, want: i128) -> f64 {
    if want == 0 {
        return if got == 0 { 0.0 } else { f64::INFINITY };
    }
    ulps(got, want) as f64 / want.unsigned_abs() as f64
}

// ---------------------------------------------------------------------------
// exp(x), x > 0
// ---------------------------------------------------------------------------

#[test]
fn positive_exp_matches_the_golden_table() {
    let mut worst_reach = (0.0f64, 0i128, 0u128);
    let mut worst_full = (0.0f64, 0i128, 0u128);
    let mut checked = 0;

    for &(x, want) in EXP_POSITIVE_GOLDEN {
        assert!(x > 0, "table must only hold positive arguments, saw {x}");
        let got = Fixed::from_raw(x)
            .exp()
            .unwrap_or_else(|e| panic!("exp(raw {x}) -> {e:?}; the table is inside the domain"))
            .to_raw();
        checked += 1;

        let r = rel(got, want);
        let u = ulps(got, want);
        if r > worst_full.0 {
            worst_full = (r, x, u);
        }
        if x <= REACHABLE_MAX_RAW && r > worst_reach.0 {
            worst_reach = (r, x, u);
        }
    }

    println!(
        "exp(x>0): {checked} points\n  \
         reachable band x<=7.7 : max rel {:.4e} at x={} ({} ulp abs)\n  \
         whole branch x<43.67  : max rel {:.4e} at x={} ({} ulp abs)",
        worst_reach.0, worst_reach.1, worst_reach.2, worst_full.0, worst_full.1, worst_full.2
    );

    assert!(
        worst_reach.0 <= REACHABLE_REL_BOUND,
        "exp rel error {:.4e} on the reachable band exceeds {REACHABLE_REL_BOUND:.1e}",
        worst_reach.0
    );
    assert!(
        worst_full.0 <= FULL_REL_BOUND,
        "exp rel error {:.4e} on the full positive branch exceeds {FULL_REL_BOUND:.1e}",
        worst_full.0
    );
    assert!(checked >= 300, "golden table shrank to {checked} points");
}

/// The range-reduction seams on their own, so a failure names the seam.
///
/// `exp(k·ln2) == 2^k` exactly, in exact arithmetic. Here `k·LN_2_RAW` uses the
/// *rounded* `LN_2_RAW`, so the true value is `2^k · e^(k·δ)` with
/// `δ = ln2 − LN_2_RAW·2^-64 ≈ 1.1e-20`; the golden table carries that. This
/// checks the two neighbours of every seam land on the same side of it as the
/// exact function does.
#[test]
fn the_range_reduction_seams_are_continuous() {
    const LN_2_RAW: i128 = 12_786_308_645_202_655_660;
    let mut worst = 0.0f64;
    for k in 1..63i128 {
        let seam = k * LN_2_RAW;
        let below = Fixed::from_raw(seam - 1).exp().unwrap().to_raw();
        let at = Fixed::from_raw(seam).exp().unwrap().to_raw();
        let above = Fixed::from_raw(seam + 1).exp().unwrap().to_raw();
        assert!(
            below <= at && at <= above,
            "exp is not monotone across seam k={k}: {below} / {at} / {above}"
        );
        // `exp(k·LN_2_RAW)` should be within a few relative ulp of 2^k.
        let two_k = 1i128 << (64 + k);
        let r = rel(at, two_k);
        worst = worst.max(r);
        assert!(
            r <= FULL_REL_BOUND,
            "exp({k}·ln2) is {at}, 2^{k} is {two_k}: rel {r:.3e}"
        );
    }
    println!("seams: max rel error vs 2^k over k=1..62 is {worst:.4e}");
}

/// A dense monotone sweep of the positive branch. A range-reduction bug that
/// the 320 sampled points happen to straddle would still show up as a step
/// backwards somewhere in 43,600 consecutive arguments.
#[test]
fn positive_exp_is_monotone_across_a_dense_sweep() {
    let one: i128 = 1i128 << 64;
    let mut prev = Fixed::ONE.to_raw();
    let mut steps = 0u32;
    for i in 1..=43_600i128 {
        let x = (i * one) / 1000; // 0.001 .. 43.6
        let e = Fixed::from_raw(x)
            .exp()
            .unwrap_or_else(|err| panic!("exp({x}) -> {err:?}"))
            .to_raw();
        assert!(
            e >= prev,
            "exp not monotone on the positive branch at raw x={x}: {e} < {prev}"
        );
        assert!(e > 0, "exp({x}) returned {e}");
        prev = e;
        steps += 1;
    }
    println!("positive monotone sweep: {steps} points, 0.001 .. 43.6");
}

/// The overflow edge, exactly. `ln(2^63) = 43.66827…`; below it `exp` must
/// succeed, above it it must return `Overflow` — never panic, never wrap.
#[test]
fn the_positive_overflow_edge_is_where_it_should_be() {
    // 43.668272375449 in Q64.64, one ulp below ln(2^63).
    const MAX_OK_RAW: i128 = 805_537_444_647_767_306_566;
    assert!(Fixed::from_raw(MAX_OK_RAW).exp().is_ok());
    assert_eq!(Fixed::from_int(44).exp(), Err(FixedError::Overflow));
    assert_eq!(Fixed::from_int(45).exp(), Err(FixedError::Overflow));
    assert_eq!(Fixed::MAX.exp(), Err(FixedError::Overflow));

    // Walk up to the first failure and check it lands in [43.66, 43.67].
    let one: i128 = 1i128 << 64;
    let mut last_ok = 0i128;
    for i in 43_600..=43_700i128 {
        let x = (i * one) / 1000;
        match Fixed::from_raw(x).exp() {
            Ok(_) => last_ok = x,
            Err(FixedError::Overflow) => break,
            Err(e) => panic!("unexpected {e:?} at raw {x}"),
        }
    }
    let cut = last_ok as f64 / 18_446_744_073_709_551_616.0;
    println!("positive exp overflow edge: last Ok at x = {cut:.6} (ln 2^63 = 43.668272)");
    assert!(
        (43.66..=43.67).contains(&cut),
        "overflow edge moved to {cut}"
    );
}

// ---------------------------------------------------------------------------
// The composite the LMSR runs
// ---------------------------------------------------------------------------

/// `exp(ln b + x)` vs `b · e^x` — the exact expression `b_small_softplus`
/// evaluates, over every `b` decade and every `x` that reaches the branch.
///
/// This is the number the LMSR's deep-skew accuracy rests on. The report
/// translates the relative bound into base units.
#[test]
fn the_scaled_softplus_term_matches_the_golden_table() {
    let mut worst = (0.0f64, 0u64, 0i128);
    let mut worst_units = 0.0f64;
    let mut checked = 0;
    let mut underflowed = 0;

    for &(b, x, want) in SCALED_EXP_GOLDEN {
        let ln_b = Fixed::from_base_units(b)
            .expect("b fits")
            .ln()
            .expect("b > 0");
        let arg = ln_b
            .checked_add(Fixed::from_raw(x))
            .expect("ln b + x cannot overflow");
        let got = arg
            .exp()
            .unwrap_or_else(|e| panic!("exp(ln {b} + raw {x}) -> {e:?}"))
            .to_raw();
        checked += 1;

        if want == 0 {
            // Both must agree that the term has vanished below half an ulp.
            assert_eq!(got, 0, "b={b} x={x}: expected underflow to 0, got {got}");
            underflowed += 1;
            continue;
        }
        let r = rel(got, want);
        if r > worst.0 {
            worst = (r, b, x);
        }
        // Absolute error in base units — the quantity that actually reaches
        // `cost` and friends.
        let err_units = ulps(got, want) as f64 / 18_446_744_073_709_551_616.0;
        worst_units = worst_units.max(err_units);
    }

    println!(
        "exp(ln b + x) vs b·e^x: {checked} points ({underflowed} correctly underflowed)\n  \
         max rel {:.4e} at b={} x_raw={}\n  \
         max abs {:.3e} base units  (1 base unit = 1e-6 USDC)",
        worst.0, worst.1, worst.2, worst_units
    );

    assert!(
        worst.0 <= COMPOSITE_REL_BOUND,
        "composite rel error {:.4e} exceeds {COMPOSITE_REL_BOUND:.1e}",
        worst.0
    );
    // The bound that matters: the softplus tail must be far below the base unit
    // the result is rounded to. Six orders of magnitude of margin is the claim.
    assert!(
        worst_units < COMPOSITE_ABS_BOUND_UNITS,
        "the scaled softplus term carries {worst_units:.3e} base units of error, above the \
         asserted {COMPOSITE_ABS_BOUND_UNITS:.0e} — it is now close enough to the 1-base-unit \
         rounding step to change a rounded answer"
    );
    assert!(checked >= 140, "golden table shrank to {checked} points");
}

/// The two ends of the reachable band, spelled out: at `b = B_MIN` the branch
/// argument is negative, at `b = B_MAX` it is `+7.63102…`. Both must evaluate.
#[test]
fn the_reachable_band_is_where_the_analysis_says_it_is() {
    let ln_bmax = Fixed::from_base_units(B_MAX).unwrap().ln().unwrap();
    let arg_max = ln_bmax.checked_add(Fixed::from_int(-20)).unwrap();
    let as_f = arg_max.to_raw() as f64 / 18_446_744_073_709_551_616.0;
    println!("b_small_softplus argument at b=B_MAX, x=-20: {as_f:.8} (ln 1e12 - 20)");
    assert!(
        arg_max.is_positive() && (7.63..7.64).contains(&as_f),
        "the positive-branch ceiling moved to {as_f}"
    );
    assert!(arg_max.exp().is_ok());
    assert!(arg_max.to_raw() <= REACHABLE_MAX_RAW);

    let ln_bmin = Fixed::from_base_units(B_MIN).unwrap().ln().unwrap();
    let arg_min = ln_bmin.checked_add(Fixed::from_int(-20)).unwrap();
    assert!(
        arg_min.is_negative(),
        "at b=B_MIN the branch argument should still be negative"
    );
}
