"""Golden tables for the **positive** branch of `Fixed::exp` (ticket T04, item 3a).

Why this exists
---------------
`crates/lmsr/gen_golden.py` (T02) characterises `exp` only on `x <= 0`, and
`fixed.rs`'s module header states T03 would never need the positive branch.
That stopped being true: T03's `b_small_softplus` evaluates `exp(ln b + x)`,
which is positive whenever `x > -ln b`, and reaches **+7.63** at `b = B_MAX`
(`ln(1e12) - 20`). The positive branch is therefore on the hot trade path and
was unmeasured.

T02's generator rewrites `crates/lmsr/src/fixed.rs` in place, and T04 does not
own `src/`. So this script writes a *test-owned* table instead:

    tests/data/exp_positive_golden.rs   (included by tests/fixed_exp_positive.rs)

Nothing in `src/` is touched. Extending the in-`src` table would require editing
`fixed.rs`; that is reported, not done.

Run (Windows CPython 3.11 + mpmath, no WSL needed):

    python crates/lmsr/tests/gen_exp_positive_golden.py
"""
import pathlib
import random

from mpmath import mp, mpf, exp, log

mp.prec = 500

S = mpf(2) ** 64
HALF = mpf(1) / 2

# Q64.64 raw of ln 2, exactly as `fixed.rs` hard-codes it. The range reduction
# steps in multiples of *this*, not of the true ln 2, so the seams sit here.
LN_2_RAW = 12_786_308_645_202_655_660

# ln(2^63): the largest argument `exp` can represent.
MAX_X = log(mpf(2) ** 63)

# Base units, mirroring `bounds.rs`.
B_MIN = 10_000_000
B_MAX = 1_000_000_000_000


def q(v):
    """Correctly-rounded Q64.64 raw value of `v`."""
    return int(mp.floor(v * S + HALF))


def real(raw):
    return mpf(raw) / S


def fmt(rows, name, ty):
    out = ["pub const %s: &[%s] = &[" % (name, ty)]
    for row in rows:
        out.append("    (" + ", ".join(str(v) for v in row) + "),")
    out.append("];")
    return "\n".join(out)


rng = random.Random(20260908)

# ---------------------------------------------------------------- exp, x > 0
xs = set()

# The smallest representable positive argument, and a spread of tiny ones.
xs.add(1)
for e in (1, 8, 16, 24, 32, 40, 48, 56, 60, 62):
    xs.add(1 << e)

# Named points: the whole reachable band, then out to the overflow edge.
named = (
    "0.000001", "0.001", "0.01", "0.1", "0.25", "0.5", "1", "1.5", "2", "3",
    "5", "7",
    # ln(B_MAX base units) - 20 : the largest argument `b_small_softplus` can
    # produce, and therefore the real ceiling of this branch.
    "7.63102111592854820821",
    "7.7", "8", "10", "15", "20", "25", "30", "35", "40", "42", "43", "43.5",
    "43.6", "43.66", "43.668",
)
for v in named:
    xs.add(q(mpf(v)))

xs.add(q(log(mpf(2))))
xs.add(q(mp.e))
xs.add(q(MAX_X) - 1)

# The range-reduction seams. `exp` splits x = n*LN_2_RAW + r and shifts left by
# n+1; a mistake in that split shows up exactly *at* a multiple of LN_2_RAW, so
# every multiple and both of its neighbours are pinned.
for n in range(0, 63):
    seam = n * LN_2_RAW
    if 0 < seam < q(MAX_X):
        xs.add(seam)
        xs.add(seam - 1)
        xs.add(seam + 1)

# Fill to 320 with uniform noise over the reachable band and the full band.
hi_reach = q(mpf("7.7"))
hi_full = q(MAX_X) - 1
while len(xs) < 320:
    if rng.random() < 0.6:
        xs.add(rng.randrange(1, hi_reach))
    else:
        xs.add(rng.randrange(1, hi_full))

exp_rows = []
for x in sorted(xs):
    if x <= 0 or x > hi_full:
        continue
    want = q(exp(real(x)))
    assert want < (1 << 127), x
    exp_rows.append((x, want))

# ------------------------------------------- the composite the LMSR evaluates
# `b_small_softplus(ln b, x)` computes `b * e^x` as `exp(ln b + x)` for
# x <= -20. This table is the end-to-end value, so it measures the ln + add +
# exp chain the trade path actually runs, not just `exp` in isolation.
bs = [B_MIN, 12_345_678, 100_000_000, 1_000_000_000, 10_000_000_000,
      100_000_000_000, 999_999_999_999, B_MAX]
scaled_rows = []
for b in bs:
    for xv in ("-20", "-20.0000001", "-21", "-22", "-25", "-27", "-27.6",
               "-27.63102111592854820821", "-28", "-30", "-35", "-40", "-44",
               "-45", "-50", "-60", "-70", "-100"):
        x = -q(-mpf(xv)) if mpf(xv) < 0 else q(mpf(xv))
        want = q(mpf(b) * exp(real(x)))
        scaled_rows.append((b, x, want))

block = "\n".join([
    "// @generated by crates/lmsr/tests/gen_exp_positive_golden.py — do not edit.",
    "//",
    "// mpmath at 500-bit precision (~150 decimal digits), correctly rounded to",
    "// Q64.64. See the generator's docstring for why this table lives in tests/.",
    "",
    "/// `(x_raw, exp(x)_raw)` for x > 0, out to ln(2^63).",
    fmt(exp_rows, "EXP_POSITIVE_GOLDEN", "(i128, i128)"),
    "",
    "/// `(b_base_units, x_raw, (b * e^x)_raw)` — the composite",
    "/// `exp(ln b + x)` that `lmsr::b_small_softplus` evaluates on the trade path.",
    fmt(scaled_rows, "SCALED_EXP_GOLDEN", "(u64, i128, i128)"),
    "",
])

out = pathlib.Path(__file__).with_name("data") / "exp_positive_golden.rs"
out.parent.mkdir(exist_ok=True)
out.write_text(block, encoding="utf-8", newline="\n")
print("exp rows:", len(exp_rows))
print("scaled rows:", len(scaled_rows))
print("max x raw:", exp_rows[-1][0], "=", mp.nstr(real(exp_rows[-1][0]), 12))
print("wrote", out)
